qrservice/urls.py
from django.contrib import admin
from django.urls import path

from .views import FeedbackView, QRListView
from django.views.generic import TemplateView


app_name = 'qrservice'

urlpatterns = [
    path('feedback/', FeedbackView.as_view()),
    path('ok/', TemplateView.as_view(template_name='qrservice/ok.html'), name='ok'),
    path('qr/all', QRListView.as_view()),
]

service_desk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('qrservice.urls', namespace='qrservice'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qrservice/models.py
from django.db import models
import uuid
from .choices import STATUSES
from .managers import QRcodeManager

class QRCode(models.Model):
    image = models.ImageField(upload_to='')
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    zone = models.ForeignKey('QRZone', on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField()


class QRZone(models.Model):
    name = models.CharField(max_length=128)
    is_active = models.BooleanField()




class Feedback(models.Model):
    qr_id = None
    text = models.CharField(max_length=512)
    name = models.CharField(max_length=128, blank=True)
    contact = models.CharField(max_length=48, blank=True)
    status = models.IntegerField(choices=STATUSES, default=1)
    objects = models.Manager()
    active_objects = QRcodeManager()




# class QRcode(models.Model):
#     unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
#     zone = models.ForeignKey('QRzone', on_delete=models.CASCADE)
# # Create your models here.

qrservice/forms.py
from django import forms

from .models import Feedback

class FeedbackForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea())
    qr_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Feedback
        fields = ['text', 'name', 'contact']

qrservice/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import FeedbackForm
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from .models import QRC


class FeedbackView(FormView):
    form_class = FeedbackForm
    template_name = 'qrservice/qr.html'
    success_url = reverse_lazy('qrservice:ok')
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class QRListView(ListView):
    model = QRCode

templates/qrservice/base.html
<!doctype html>
{%load staticfiles%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Floating labels example · Bootstrap</title>



    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.4/examples/floating-labels/floating-labels.css" rel="stylesheet">
  </head>
  <body>
  {%block content%}
  {%endblock content%}
  </body>
  </html>

templates/qrservice/ok.html
{%extends 'qrservice/base.html'%}
{%load staticfiles%}
{%block content%}
<h1>ok</h1>
<div><img src= "{%static 'images\IMG_0629.jpg'%}", alt= "" width = "150px", height="125px"></div>

{%endblock content%}

templates/qrservice/qr.html
{%extends 'qrservice/base.html'%}
{%block content%}
{%load staticfiles%}

    <form method="post" class="form-signin">{% csrf_token %}
        <div><img src= "{%static 'images\IMG_0629.jpg'%}", alt= "" width = "150px", height="125px"></div>
          <div class="text-center mb-4">
            <img class="mb-4" src="{static 'url'}" alt="" width="150">
            <h1 class="h3 mb-3 font-weight-normal">Есть что сказать?</h1>
            <p>Опиши всё, что думаешь</p>
          </div>
        <div class="form-label-group">
            {{ form.text }}
            {{ form.text.errors }}
        </div>

        <div class="custom-control custom-switch">
          <input type="checkbox" class="custom-control-input" id="switch" onclick="if(this.checked){document.getElementById('hidden').style.display='block';} else {document.getElementById('hidden').style.display='none';}">
          <label class="custom-control-label" for="switch">Оставить контакты</label>
        </div>
        <div id="hidden" style="display: none;">
            <div class="form-label-group">
                {{ form.name }}
                {{ form.name.errors }}
                <label for="id_name">Имя</label>
            </div>

            <div class="form-label-group">
                {{ form.contact }}
                {{ form.contact.errors }}
                <label for="id_contact">Контакт</label>
            </div>
        </div>
        <button class="btn btn-lg btn-secondary btn-block" type="submit">Отправить</button>

        <p class="mt-5 mb-3 text-muted text-center">политика конфиденциальности</p>
    </form>
{%endblock content%}

templates/qrservice/qrcode_list.html
{%extends 'qrservice/base.html'%}
{%load qr_code%}
{%block content%}

<ul>
	{%for qrcode in object_list%}
		<li>
		{%qr_from_text 'hi' %}
			{{qrcode.unique_id}}
		{%empty%}
		<p>Нет QR-кодов</p>
	</li>
	{%endfor%}
	</ul>
{%endblock content%}


<!--<li><img src="{{qrcode.image.url}}", alt= "" width = "150px", height="125px"/><span></span></li>-->